# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.TextField()),
                ('act', models.TextField()),
                ('utt', models.TextField()),
            ],
        ),
    ]
